### ISSUE TITLE
0.0.3 Checklist

### ISSUE THREAD

**Issue by kc611** [numba/numba-rvsdg#72]
This issue serves as a checklist for the things/features that we want for the 0.0.3 release.

- [ ] https://github.com/numba/numba-rvsdg/issues/71
- [ ] https://github.com/numba/numba-rvsdg/issues/66
- [ ] https://github.com/numba/numba-rvsdg/issues/64
- [ ] https://github.com/numba/numba-rvsdg/issues/63
- [ ] https://github.com/numba/numba-rvsdg/issues/73
- [ ] https://github.com/numba/numba-rvsdg/issues/75

**Comment by esc** [comment]
Closing in favour of: https://github.com/numba/numba-rvsdg/milestone/1
